# Generated by Django 5.2.13 on 2026-04-08 07:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vai_tro', models.CharField(max_length=50)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vai_tro',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('ho_ten', models.CharField(max_length=150)),
                ('gioi_tinh', models.CharField(blank=True, choices=[('NAM', 'Nam'), ('NU', 'Nữ')], max_length=3, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('kich_hoat', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('vai_tro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vaitro')),
            ],
            options={
                'db_table': 'tai_khoan',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HoSoBacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kich_hoat', models.BooleanField(default=True)),
                ('ma_bac_si', models.CharField(max_length=20, unique=True)),
                ('bang_cap', models.CharField(blank=True, max_length=255, null=True)),
                ('chung_chi', models.TextField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('phi_tu_van', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ho_so_bac_si',
            },
        ),
        migrations.CreateModel(
            name='HoSoBenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kich_hoat', models.BooleanField(default=True)),
                ('ma_benh_nhan', models.CharField(max_length=20, unique=True)),
                ('nhom_mau', models.CharField(blank=True, max_length=10, null=True)),
                ('tien_su_benh', models.TextField(blank=True, null=True)),
                ('bao_hiem_y_te', models.CharField(blank=True, max_length=50, null=True)),
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ho_so_benh_nhan',
            },
        ),
    ]
