# Generated by Django 6.0.3 on 2026-04-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='specialty',
            table='specialty',
        ),
    ]
