# Generated by Django 5.2.14 on 2026-05-21 14:40

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_remove_nurse_user_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='servicesspecialty',
            old_name='Specialty',
            new_name='specialties',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('nurse', 'Y tá')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='polyclinic.staffprofile'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('disease_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('in_progress', 'Đang khám'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='appointment_services', to='polyclinic.servicesspecialty')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_time_slot', to='polyclinic.timeslot')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='polyclinic.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.TextField()),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='polyclinic.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('ingredient', models.TextField(blank=True, help_text='Hoạt chất', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('tablet', 'Viên'), ('capsule', 'Nang'), ('bottle', 'Chai'), ('tube', 'Tuýp'), ('vial', 'Lọ tiêm'), ('pack', 'Gói'), ('other', 'Khác')], default='tablet', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='polyclinic.medicinecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Lưu ý chung của đơn thuốc', null=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medical_record', to='polyclinic.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.TextField()),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results', to='polyclinic.medicalrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Tổng số lượng')),
                ('dosage', models.CharField(help_text='Liều mỗi lần, vd: 1 viên, 2 viên', max_length=50)),
                ('frequency', models.CharField(choices=[('1x_day', '1 lần/ngày'), ('2x_day', '2 lần/ngày'), ('3x_day', '3 lần/ngày'), ('4x_day', '4 lần/ngày'), ('as_needed', 'Khi cần')], max_length=20)),
                ('timing', models.CharField(blank=True, choices=[('before_meal', 'Trước ăn'), ('after_meal', 'Sau ăn'), ('with_meal', 'Trong khi ăn'), ('bedtime', 'Trước khi ngủ')], max_length=20)),
                ('duration_days', models.IntegerField(help_text='Số ngày uống')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú riêng cho thuốc này', null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='polyclinic.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='polyclinic.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'medicine')},
            },
        ),
    ]
