# Generated by Django 5.2.14 on 2026-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị'), ('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('nurse', 'Y tá')], default='patient', max_length=10),
        ),
    ]
