# Generated by Django 5.2.13 on 2026-04-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacSiChuyenKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bac_si_chuyen_khoa',
            },
        ),
        migrations.CreateModel(
            name='ChuyenKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ma_ck', models.CharField(max_length=20, unique=True)),
                ('ten_ck', models.CharField(max_length=150)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('kich_hoat', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chuyen_khoa',
            },
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kich_hoat', models.BooleanField(default=True)),
                ('ma_lich_hen', models.CharField(max_length=30, unique=True)),
                ('ngay_hen', models.DateField()),
                ('gio_hen', models.TimeField()),
                ('ly_do_kham', models.TextField(blank=True, null=True)),
                ('hinh_thuc', models.CharField(choices=[('TRUC_TIEP', 'Trực tiếp'), ('TRUC_TUYEN', 'Trực tuyến')], default='TRUC_TIEP', max_length=20)),
                ('link_video', models.CharField(blank=True, max_length=500, null=True)),
                ('trang_thai', models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_XAC_NHAN', 'Đã xác nhận'), ('HOAN_THANH', 'Hoàn thành'), ('HUY', 'Hủy')], default='CHO_XAC_NHAN', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lich_hen',
            },
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_lam_viec', models.DateField()),
                ('gio_bat_dau', models.TimeField()),
                ('gio_ket_thuc', models.TimeField()),
                ('tong_slot', models.IntegerField(default=0)),
                ('kich_hoat', models.BooleanField(default=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lich_lam_viec',
            },
        ),
    ]
