# Generated by Django 5.2.13 on 2026-04-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacsichuyenkhoa',
            name='bac_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hosobacsi'),
        ),
        migrations.AddField(
            model_name='bacsichuyenkhoa',
            name='chuyen_khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.chuyenkhoa'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hosobenhnhan'),
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='bac_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hosobacsi'),
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='chuyen_khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.chuyenkhoa'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='lich_lv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.lichlamviec'),
        ),
        migrations.AlterUniqueTogether(
            name='bacsichuyenkhoa',
            unique_together={('bac_si', 'chuyen_khoa')},
        ),
        migrations.AlterUniqueTogether(
            name='lichlamviec',
            unique_together={('bac_si', 'ngay_lam_viec', 'gio_bat_dau')},
        ),
    ]
